---
sidebar: sidebar 
permalink: faq-cloud-tiering.html 
keywords: faq, questions, requirements, service connector, agent, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent, agent, netapp console, console,cloud tier 
summary: 質問に対する簡単な回答を探している場合は、この FAQ が役立ちます。 
---
= NetApp Cloud Tiering技術 FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この FAQ は、NetApp Cloud Tieringに関する質問への簡単な回答を探している場合に役立ちます。



== クラウド階層化サービス

次の FAQ は、クラウド階層化の仕組みに関するものです。



=== Cloud Tiering サービスを使用する利点は何ですか?

クラウド階層化は、急速なデータ増加に伴う課題に対処し、次のようなメリットをもたらします。

* クラウドへのデータセンターの拡張が容易になり、最大50倍のスペースを提供
* ストレージの最適化により、平均70%のストレージ節約を実現
* 総所有コストを平均30%削減
* アプリケーションをリファクタリングする必要はありません




=== クラウドに階層化するのに有用なデータの種類は何ですか?

基本的に、プライマリ ストレージ システムとセカンダリ ストレージ システムの両方で非アクティブであると見なされるデータは、クラウドに移動するのに適した対象です。プライマリ システムでは、このようなデータにはスナップショット、履歴レコード、完了したプロジェクトなどが含まれる場合があります。セカンダリ システムでは、DR およびバックアップの目的で作成されたプライマリ データのコピーを含むすべてのボリュームが含まれます。



=== NAS ボリュームと SAN ボリュームの両方からデータを階層化できますか?

はい、NAS ボリュームからパブリック クラウドまたはStorageGRIDなどのプライベート クラウドにデータを階層化できます。  SAN プロトコルでアクセスされるデータを階層化する場合、SAN プロトコルは NAS よりも接続の問題の影響を受けやすいため、 NetAppプライベート クラウドの使用を推奨しています。



=== 非アクティブなデータまたはあまり使用されないデータの定義は何ですか? また、それはどのように制御されますか?

コールド データとも呼ばれる定義は、「一定期間アクセスされていないボリューム ブロック (メタデータは除く)」です。  「時間量」は、cooling-days という階層化ポリシー属性によって決まります。



=== Cloud Tiering では、クラウド層でのストレージ効率の節約は維持されますか?

はい、データをクラウド層に移動するときに、圧縮、重複排除、コンパクションなどのONTAPボリューム レベルのストレージ効率が維持されます。



=== FabricPoolと Cloud Tiering の違いは何ですか?

FabricPool は、 ONTAP CLI および System Manager を通じて自己管理することも、Cloud Tiering を通じてサービスとして管理することもできるONTAP階層化テクノロジーです。  Cloud Tiering は、 ONTAPとクラウドの両方でFabricPool を高度な自動化プロセスを備えたマネージド サービスに変換し、ハイブリッドおよびマルチクラウドの展開全体にわたって階層化の可視性と制御を向上させます。



=== クラウドに階層化されたデータは、災害復旧やバックアップ/アーカイブに使用できますか?

いいえ。ボリュームのメタデータはパフォーマンス層から階層化されることはないため、オブジェクト ストレージに保存されているデータに直接アクセスすることはできません。

ただし、クラウド階層化を使用すると、セカンダリ システムとSnapMirror宛先ボリューム (DP ボリューム) で有効にしてすべてのデータ (メタデータは除く) を階層化し、データセンターの占有スペースと TCO を削減することで、コスト効率の高いバックアップと DR を実現できます。



=== クラウド階層化はボリューム レベルまたは集約レベルで適用されますか?

クラウド階層化は、階層化ポリシーを各ボリュームに関連付けることでボリューム レベルで有効化されます。コールド データの識別はブロック レベルで行われます。



=== Cloud Tiering では、どのブロックをクラウドに階層化するかをどのように決定しますか?

ボリュームに関連付けられた階層化ポリシーは、どのブロックをいつ階層化するかを制御するメカニズムです。ポリシーは、データ ブロックの種類 (スナップショット、ユーザー データ、またはその両方) と冷却期間を定義します。見るlink:concept-cloud-tiering.html#volume-tiering-policies["ボリューム階層化ポリシー"]詳細については。



=== クラウド階層化はボリューム容量にどのような影響を与えますか?

クラウド階層化はボリュームの容量には影響しませんが、アグリゲートのパフォーマンス層の使用に影響します。



=== クラウド階層化により非アクティブ データのレポートは有効になりますか?

はい、クラウド階層化により、各アグリゲートで非アクティブ データ レポート (IDR) が有効になります。この設定により、低コストのオブジェクト ストレージに階層化できる非アクティブ データの量を識別できます。



=== IDR の実行を開始してから情報が表示されるまでどのくらいの時間がかかりますか?

IDR は、設定された冷却期間が経過した後に情報を表示し始めます。  ONTAP 9.7 以前では、IDR の冷却期間は 31 日間で調整できませんでした。  ONTAP 9.8 以降では、IDR 冷却期間を最大 183 日まで設定できます。



== ライセンスとコスト

次の FAQ は、Cloud Tiering を使用するためのライセンスとコストに関するものです。



=== Cloud Tiering の使用にはどれくらいの費用がかかりますか?

コールドデータをパブリック クラウドに階層化する場合:

* 従量課金制 (PAYGO) の使用量ベースのサブスクリプションの場合: 1 GB/月あたり 0.05 ドル。
* 年間 (BYOL)、期間ベースのサブスクリプションの場合: 1 GB/月あたり 0.033 ドルから。


https://bluexp.netapp.com/pricing["価格の詳細を見る"]。

コールド データをNetApp StorageGRIDシステム (プライベート クラウド) に階層化する場合、コストはかかりません。



=== 同じONTAPクラスターに対して BYOL ライセンスと PAYGO ライセンスの両方を持つことはできますか?

○Cloud Tiering を使用すると、BYOL ライセンス、PAYGO サブスクリプション、またはその両方の組み合わせを使用できます。



=== BYOL 容量制限に達した場合、または BYOL ライセンスの有効期限が切れた場合はどうなりますか?

BYOL 容量制限に達した場合、または BYOL ライセンスの有効期限が切れた場合、新しいコールド データの階層化は停止します。以前に階層化されたデータはすべて引き続きアクセス可能であり、このデータを取得して使用できます。取得されると、このデータはクラウドからパフォーマンス層に戻されます。

ただし、_BlueXP - クラウド データ サービスのデプロイと管理_ の PAYGO マーケットプレイス サブスクリプションをお持ちの場合は、新しいコールド データは引き続きオブジェクト ストレージに階層化され、使用量に応じて料金を支払うことになります。



=== Cloud Tiering ライセンスには、クラウド プロバイダーからの送信料金が含まれていますか?

いいえ、違います。



=== オンプレミス システムのリハイドレーションは、クラウド プロバイダーによって請求されるエグレス コストの対象になりますか?

○パブリック クラウドからのすべての読み取りには、送信料金がかかります。



=== クラウド料金を見積もるにはどうすればいいですか?  Cloud Tiering には「what if」モードがありますか?

クラウド プロバイダーがデータのホスティングに対して請求する料金を見積もる最良の方法は、プロバイダーの計算ツールを使用することです。 https://calculator.aws/#/["AWS"] 、 https://azure.microsoft.com/en-us/pricing/calculator/["Azure"]そして https://cloud.google.com/products/calculator["Google Cloud"]。



=== オブジェクト ストレージからオンプレミス ストレージへのデータの読み取り/取得に対して、クラウド プロバイダーから追加料金が発生しますか?



=== オブジェクト ストレージからオンプレミス ストレージへのデータの読み取り/取得に対して、クラウド プロバイダーから追加料金が発生しますか?

○チェック https://aws.amazon.com/s3/pricing/["Amazon S3 の料金"]、 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["ブロックブロブの価格"] 、 そして https://cloud.google.com/storage/pricing["クラウドストレージの料金"]データの読み取り/取得に伴う追加料金が発生します。



=== クラウド階層化を有効にする前に、ボリュームの節約量を見積もってコールド データ レポートを取得するにはどうすればよいですか?

見積りを取得するには、 ONTAPクラスターをNetApp Consoleに追加し、クラウド階層化クラスター ページから検査します。クラスタの「潜在的な階層化による節約を計算」を選択して起動します。 https://bluexp.netapp.com/cloud-tiering-service-tco["クラウド階層化TCO計算ツール"^]どれだけお金を節約できるか確認しましょう。



=== ONTAP MetroClusterを使用している場合、階層化に対してどのように課金されますか?

MetroCluster環境で使用する場合、両方のクラスターの使用に対して合計階層化ライセンスが適用されます。たとえば、100TiB の階層化ライセンスがある場合、各クラスターの使用済み階層化容量は合計容量 100TiB に加算されます。



== ONTAP

次の質問はONTAPに関連しています。



=== Cloud Tiering はどのONTAPバージョンをサポートしていますか?

Cloud Tiering はONTAPバージョン 9.2 以降をサポートしています。



=== どのようなタイプのONTAPシステムがサポートされていますか?

クラウド階層化は、単一ノードおよび高可用性のAFF、 FAS、およびONTAP Selectクラスターでサポートされています。  FabricPoolミラー構成およびMetroCluster構成のクラスターもサポートされています。



=== FASシステムからのデータを HDD のみで階層化できますか?

はい、 ONTAP 9.8 以降では、HDD アグリゲートでホストされているボリュームからデータを階層化できます。



=== HDD を搭載したFASノードを持つクラスターに結合されたAFFからデータを階層化できますか?

○クラウド階層化は、任意のアグリゲート上でホストされているボリュームを階層化するように構成できます。データ階層化構成は、使用されるコントローラーのタイプやクラスターが異種であるかどうかとは無関係です。



=== Cloud Volumes ONTAPについてはどうですか?

Cloud Volumes ONTAPシステムをお持ちの場合は、Cloud Tiering Clusters ページでそれらを見つけることができるため、ハイブリッド クラウド インフラストラクチャのデータ階層化の全体像を把握できます。ただし、 Cloud Volumes ONTAPシステムは、Cloud Tiering からは読み取り専用です。  Cloud Tiering からCloud Volumes ONTAPにデータ階層化を設定することはできません。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html["NetApp ConsoleのONTAPシステムからCloud Volumes ONTAPシステムの階層化を設定します。"^] 。



=== ONTAPクラスタには他にどのような要件が必要ですか?

コールドデータをどこに階層化するかによって異なります。詳細については、次のリンクを参照してください。

* link:task-tiering-onprem-aws.html#prepare-your-ontap-cluster["Amazon S3へのデータの階層化"]
* link:task-tiering-onprem-azure.html#preparing-your-ontap-clusters["Azure Blob ストレージへのデータの階層化"]
* link:task-tiering-onprem-gcp.html#preparing-your-ontap-clusters["Google Cloud Storage へのデータの階層化"]
* link:task-tiering-onprem-storagegrid.html#preparing-your-ontap-clusters["StorageGRIDへのデータの階層化"]
* link:task-tiering-onprem-s3-compat.html#preparing-your-ontap-clusters["S3 オブジェクトストレージへのデータの階層化"]




== オブジェクト ストレージ

次の質問はオブジェクト ストレージに関するものです。



=== どのオブジェクト ストレージ プロバイダーがサポートされていますか?

Cloud Tiering は、次のオブジェクト ストレージ プロバイダーをサポートしています。

* Amazon S3
* Microsoft Azure ブロブ
* Google Cloud Storage
* NetAppStorageGRID
* S3互換オブジェクトストレージ（例：MinIO）
* IBM Cloud Object Storage ( FabricPoolの構成は System Manager またはONTAP CLI を使用して行う必要があります)




=== 自分のバケツ/コンテナを使用できますか?

はい、できます。データ階層化を設定するときに、新しいバケット/コンテナを追加するか、既存のバケット/コンテナを選択するかを選択できます。



=== どの地域がサポートされていますか?

* link:reference-aws-support.html["サポートされているAWSリージョン"]
* link:reference-azure-support.html["サポートされているAzureリージョン"]
* link:reference-google-support.html["サポートされている Google Cloud リージョン"]




=== どの S3 ストレージ クラスがサポートされていますか?

Cloud Tiering は、_Standard_、_Standard-Infrequent Access_、_One Zone-Infrequent Access_、_Intelligent Tiering_、および _Glacier Instant Retrieval_ ストレージ クラスへのデータ階層化をサポートします。見るlink:reference-aws-support.html["サポートされているS3ストレージクラス"]詳細についてはこちらをご覧ください。



=== Amazon S3 Glacier Flexible と S3 Glacier Deep Archive が Cloud Tiering でサポートされていないのはなぜですか?

Amazon S3 Glacier Flexible と S3 Glacier Deep Archive がサポートされていない主な理由は、Cloud Tiering が高性能な階層化ソリューションとして設計されているため、データが継続的に利用可能であり、取得のためにすぐにアクセスできる必要があるためです。  S3 Glacier Flexible と S3 Glacier Deep Archive を使用すると、データの取得には数分から 48 時間かかる場合があります。



=== MinIO などの他の S3 互換オブジェクト ストレージ サービスを Cloud Tiering で使用できますか?

はい、Tiering UI を介した S3 互換オブジェクト ストレージの構成は、 ONTAP 9.8 以降を使用するクラスターでサポートされています。link:task-tiering-onprem-s3-compat.html["詳細はこちら"] 。



=== どの Azure Blob アクセス層がサポートされていますか?

Cloud Tiering は、非アクティブなデータに対して _Hot_ または _Cool_ アクセス層へのデータ階層化をサポートします。見るlink:reference-azure-support.html["サポートされている Azure BLOB アクセス層"]詳細についてはこちらをご覧ください。



=== Google Cloud Storage ではどのストレージ クラスがサポートされていますか?

Cloud Tiering は、_Standard_、_Nearline_、_Coldline_、_Archive_ ストレージ クラスへのデータ階層化をサポートします。見るlink:reference-google-support.html["サポートされている Google Cloud ストレージ クラス"]詳細についてはこちらをご覧ください。



=== Cloud Tiering はライフサイクル管理ポリシーの使用をサポートしていますか?

○ライフサイクル管理を有効にすると、一定の日数後に Cloud Tiering によってデータがデフォルトのストレージ クラス/アクセス層からよりコスト効率の高い層に移行されます。ライフサイクル ルールは、Amazon S3 および Google Cloud ストレージの場合は選択したバケット内のすべてのオブジェクトに適用され、Azure Blob の場合は選択したストレージ アカウント内のすべてのコンテナに適用されます。



=== Cloud Tiering では、クラスター全体に 1 つのオブジェクト ストアを使用しますか、それとも集約ごとに 1 つのオブジェクト ストアを使用しますか?

一般的な構成では、クラスター全体に対して 1 つのオブジェクト ストアが存在します。  2022 年 8 月からは、*詳細設定* ページを使用してクラスターにオブジェクト ストアを追加し、異なるオブジェクト ストアを異なるアグリゲートに接続したり、ミラーリングのために 2 つのオブジェクト ストアをアグリゲートに接続したりできるようになります。



=== 同じアグリゲートに複数のバケットを接続できますか?

ミラーリングを目的として、アグリゲートごとに最大 2 つのバケットを接続でき、コールド データは両方のバケットに同期的に階層化されます。バケットは、異なるプロバイダーや異なる場所からのものである可能性があります。  2022 年 8 月からは、「*詳細設定*」ページを使用して、2 つのオブジェクト ストアを 1 つのアグリゲートに接続できるようになります。



=== 同じクラスター内の異なるアグリゲートに異なるバケットを接続できますか?

○一般的なベスト プラクティスは、単一のバケットを複数のアグリゲートにアタッチすることです。ただし、パブリック クラウドを使用する場合、オブジェクト ストレージ サービスには最大 IOPS 制限があるため、複数のバケットを考慮する必要があります。



=== ボリュームをあるクラスターから別のクラスターに移行すると、階層化されたデータはどうなるのでしょうか?

ボリュームをあるクラスターから別のクラスターに移行すると、すべてのコールド データがクラウド層から読み取られます。宛先クラスター上の書き込み場所は、階層化が有効になっているかどうかと、ソース ボリュームと宛先ボリュームで使用される階層化ポリシーの種類によって異なります。



=== 同じクラスター内のあるノードから別のノードにボリュームを移動すると、階層化されたデータはどうなるのでしょうか?

宛先アグリゲートにクラウド層が接続されていない場合、データはソース アグリゲートのクラウド層から読み取られ、宛先アグリゲートのローカル層に完全に書き込まれます。宛先アグリゲートにクラウド層が接続されている場合、迅速な切り替えを容易にするために、データはソース アグリゲートのクラウド層から読み取られ、最初に宛先アグリゲートのローカル層に書き込まれます。その後、使用された階層化ポリシーに基づいて、クラウド層に書き込まれます。

ONTAP 9.6 以降では、宛先アグリゲートがソース アグリゲートと同じクラウド層を使用している場合、コールド データはローカル層に戻りません。



=== 階層化されたデータをオンプレミスのパフォーマンス層に戻すにはどうすればよいですか?

ライトバックは通常、読み取り時に実行され、階層化ポリシーのタイプによって異なります。  ONTAP 9.8 より前では、ボリューム全体の書き戻しは、_volume move_ 操作で実行できます。 ONTAP 9.8 以降、階層化 UI には、*すべてのデータを復元*または*アクティブなファイル システムを復元*するオプションがあります。link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier["データをパフォーマンス層に戻す方法をご覧ください"] 。



=== 既存のAFF/ FASコントローラーを新しいコントローラーに交換する場合、階層化されたデータはオンプレミスに移行されますか?

いいえ。「ヘッド スワップ」手順中に変更されるのは、アグリゲートの所有権のみです。この場合、データの移動は行われず、新しいコントローラーに変更されます。



=== クラウド プロバイダーのコンソールまたはオブジェクト ストレージ エクスプローラーを使用して、バケットに階層化されたデータを確認できますか?  ONTAPを使用せずに、オブジェクト ストレージに保存されたデータを直接使用できますか?

いいえ。クラウドに構築され階層化されたオブジェクトには、単一のファイルではなく、複数のファイルからの最大 1,024 個の 4 KB ブロックが含まれます。ボリュームのメタデータは常にローカル層に残ります。



== コンソールエージェント

次の質問はコンソール エージェントに関するものです。



=== コンソールエージェントとは何ですか?

コンソール エージェントは、クラウド アカウント内またはオンプレミスのコンピューティング インスタンスで実行されるソフトウェアであり、 NetApp Consoleがクラウド リソースを安全に管理できるようにします。Cloud Tiering サービスを使用するには、エージェントを展開する必要があります。



=== コンソール エージェントはどこにインストールする必要がありますか?

* データを S3 に階層化する場合、エージェントは AWS VPC またはオンプレミスに配置できます。
* データを Blob ストレージに階層化する場合、エージェントは Azure VNet またはオンプレミスに配置できます。
* データを Google Cloud Storage に階層化する場合、エージェントは Google Cloud Platform VPC 内に存在している必要があります。
* StorageGRIDまたはその他の S3 互換ストレージ プロバイダーにデータを階層化する場合、エージェントはオンプレミスに常駐する必要があります。




=== コンソール エージェントをオンプレミスに展開できますか?

○エージェント ソフトウェアは、ネットワーク内の Linux ホストにダウンロードして手動でインストールできます。 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["エージェントを社内にインストールする方法をご覧ください"] 。



=== Cloud Tiering を使用する前に、クラウド サービス プロバイダーのアカウントは必要ですか?

○使用するオブジェクト ストレージを定義するには、アカウントが必要です。  VPC または VNet 上のクラウドにエージェントを設定する場合は、クラウド ストレージ プロバイダーのアカウントも必要です。



=== コンソール エージェントに障害が発生した場合、どのような影響がありますか?

エージェントに障害が発生した場合、階層化された環境への可視性のみが影響を受けます。すべてのデータにアクセス可能であり、新しく識別されたコールド データは自動的にオブジェクト ストレージに階層化されます。



== 階層化ポリシー



=== 利用可能な階層化ポリシーは何ですか?

階層化ポリシーには次の 4 つがあります。

* なし: すべてのデータを常にホットとして分類し、ボリュームのデータがオブジェクト ストレージに移動されるのを防ぎます。
* コールド スナップショット (スナップショットのみ): コールド スナップショット ブロックのみがオブジェクト ストレージに移動されます。
* コールド ユーザー データとスナップショット (自動): コールド スナップショット ブロックとコールド ユーザー データ ブロックの両方がオブジェクト ストレージに移動されます。
* すべてのユーザー データ (すべて): すべてのデータをコールドとして分類し、ボリューム全体を直ちにオブジェクト ストレージに移動します。


link:concept-cloud-tiering.html#volume-tiering-policies["階層化ポリシーの詳細"]。



=== どの時点でデータがコールドであるとみなされるのでしょうか?

データ階層化はブロック レベルで行われるため、階層化ポリシーの minimum-cooling-days 属性によって定義された一定期間アクセスされていないデータ ブロックはコールド状態であると見なされます。適用範囲は、 ONTAP 9.7 以前では 2 ～ 63 日、 ONTAP 9.8 以降では 2 ～ 183 日です。



=== データがクラウド層に階層化される前のデフォルトの冷却期間はどれくらいですか?

コールド スナップショット ポリシーのデフォルトの冷却期間は 2 日間ですが、コールド ユーザー データとスナップショットのデフォルトの冷却期間は 31 日間です。冷却日数パラメータは、すべての階層化ポリシーには適用されません。



=== 完全バックアップを実行すると、階層化されたすべてのデータがオブジェクト ストレージから取得されますか?

完全バックアップ中は、すべてのコールド データが読み取られます。データの取得は、使用される階層化ポリシーによって異なります。すべてのユーザーデータとスナップショットのポリシーを使用する場合、コールド データはパフォーマンス層に書き戻されません。コールド スナップショット ポリシーを使用する場合、バックアップに古いスナップショットが使用されている場合にのみ、そのコールド ブロックが取得されます。



=== ボリュームごとに階層サイズを選択できますか?

いいえ。ただし、階層化の対象となるボリューム、階層化されるデータの種類、およびその冷却期間を選択することはできます。これは、階層化ポリシーをそのボリュームに関連付けることによって行われます。



=== データ保護ボリュームのオプションは「すべてのユーザー データ」ポリシーのみですか?

いいえ。データ保護 (DP) ボリュームは、使用可能な 3 つのポリシーのいずれかに関連付けることができます。ソース ボリュームと宛先ボリューム (DP) で使用されるポリシーの種類によって、データの書き込み場所が決まります。



=== ボリュームの階層化ポリシーを「なし」にリセットすると、コールド データが復元されますか、それとも将来のコールド ブロックがクラウドに移動されなくなるだけですか?

階層化ポリシーがリセットされると再水和は行われませんが、新しいコールド ブロックがクラウド層に移動されなくなります。



=== データをクラウドに階層化した後、階層化ポリシーを変更できますか?

○変更後の動作は、新しい関連ポリシーによって異なります。



=== 特定のデータがクラウドに移動されないようにしたい場合はどうすればよいでしょうか?

そのデータを含むボリュームに階層化ポリシーを関連付けないでください。



=== ファイルのメタデータはどこに保存されますか?

ボリュームのメタデータは常にパフォーマンス層にローカルに保存され、クラウドに階層化されることはありません。



== ネットワークとセキュリティ

次の質問はネットワークとセキュリティに関するものです。



=== ネットワーク要件は何ですか?

* ONTAPクラスターは、ポート 443 経由でオブジェクト ストレージ プロバイダーへの HTTPS 接続を開始します。
+
ONTAP はオブジェクト ストレージとの間でデータの読み取りと書き込みを行います。オブジェクト ストレージは開始することはなく、応答するだけです。

* StorageGRIDの場合、 ONTAPクラスタは、ユーザ指定のポートを介してStorageGRIDへの HTTPS 接続を開始します (ポートは階層化セットアップ中に構成可能です)。
* エージェントには、 ONTAPクラスター、オブジェクト ストア、および Cloud Tiering サービスへのポート 443 経由の送信 HTTPS 接続が必要です。


詳細については、以下を参照してください。

* link:task-tiering-onprem-aws.html["Amazon S3へのデータの階層化"]
* link:task-tiering-onprem-azure.html["Azure Blob ストレージへのデータの階層化"]
* link:task-tiering-onprem-gcp.html["Google Cloud Storage へのデータの階層化"]
* link:task-tiering-onprem-storagegrid.html["StorageGRIDへのデータの階層化"]
* link:task-tiering-onprem-s3-compat.html["S3 オブジェクトストレージへのデータの階層化"]




=== クラウドに保存されているコールド データを管理するために、監視とレポートに使用できるツールは何ですか?

クラウド階層化以外にも、 https://docs.netapp.com/us-en/active-iq-unified-manager/["Active IQ Unified Manager"^]そして https://docs.netapp.com/us-en/active-iq/index.html["デジタルアドバイザー"^]監視およびレポートに使用できます。



=== クラウド プロバイダーへのネットワーク リンクに障害が発生した場合、どのような影響がありますか?

ネットワーク障害が発生した場合でも、ローカル パフォーマンス層はオンラインのままとなり、ホット データへのアクセスが維持されます。ただし、すでにクラウド層に移動されているブロックにはアクセスできず、アプリケーションがそのデータにアクセスしようとするとエラー メッセージが表示されます。接続が回復すると、すべてのデータにシームレスにアクセスできるようになります。



=== ネットワーク帯域幅の推奨事項はありますか?

基盤となるFabricPool階層化テクノロジの読み取り待機時間は、クラウド層への接続によって異なります。階層化はどの帯域幅でも機能しますが、適切なパフォーマンスを提供するために、クラスタ間 LIF を 10 Gbps ポートに配置することをお勧めします。エージェントには推奨事項や帯域幅の制限はありません。

さらに、ボリュームからオブジェクト ストレージへの非アクティブなデータの転送中に使用されるネットワーク帯域幅の量を調整することもできます。  _最大転送速度_ 設定は、階層化用にクラスターを構成するときに使用でき、その後は *クラスター* ページから使用できます。



=== ユーザーが階層化されたデータにアクセスしようとしたときに遅延は発生しますか?

○レイテンシは接続性に依存するため、クラウド層ではローカル層と同じレイテンシを提供できません。オブジェクト ストアのレイテンシとスループットを見積もるために、Cloud Tiering は、オブジェクト ストアが接続された後、階層化がセットアップされる前に使用できるクラウド パフォーマンス テスト ( ONTAPオブジェクト ストア プロファイラーに基づく) を提供します。



=== データはどのように保護されますか?

AES-256-GCM 暗号化は、パフォーマンス層とクラウド層の両方で維持されます。  TLS 1.2 暗号化は、階層間を移動するデータをネットワーク経由で暗号化するため、およびエージェントとONTAPクラスタおよびオブジェクト ストア間の通信を暗号化するために使用されます。



=== AFFにイーサネット ポートをインストールして構成する必要がありますか?

○クラウドに階層化する予定のデータを含むボリュームをホストする HA ペア内の各ノードのイーサネット ポートに、クラスタ間 LIF を構成する必要があります。詳細については、データを階層化する予定のクラウド プロバイダーの要件セクションを参照してください。



=== どのような権限が必要ですか?

* link:task-tiering-onprem-aws.html#set-up-s3-permissions["Amazonの場合、S3バケットを管理するには権限が必要です"]。
* Azure の場合、 NetApp Consoleに提供する必要がある権限以外に追加の権限は必要ありません。
* link:task-tiering-onprem-gcp.html#preparing-google-cloud-storage["Google Cloud では、ストレージ アクセス キーを持つサービス アカウントにストレージ管理者権限が必要です。"]。
* link:task-tiering-onprem-storagegrid.html#preparing-storagegrid["StorageGRIDの場合、S3権限が必要です"]。
* link:task-tiering-onprem-s3-compat.html#preparing-s3-compatible-object-storage["S3互換オブジェクトストレージにはS3権限が必要です"]。

